### ISSUE TITLE
bb: not found

### ISSUE THREAD

**Issue by tfrancart** [logseq/rdf-export#1]
Completely new to logseq here, eager to test the RDF export feature.
Tried to install as documented, but got the following error:

```
thomas@thomas-ThinkPad-T14-Gen-1:~/programs/logseq/data$ logseq-rdf-export docs.ttl
Downloading dependencies...
/bin/sh: 1: bb: not found
child_process.js:790
    err = new Error(msg);
          ^

Error: Command failed: bb --config /home/thomas/.config/yarn/global/node_modules/@logseq/rdf-export/.nbb/.cache/4ef27996850f7cca83b8c016709fa38b9216264a/deps.edn uberjar /home/thomas/.config/yarn/global/node_modules/@logseq/rdf-export/.nbb/.cache/4ef27996850f7cca83b8c016709fa38b9216264a/nbb-deps.jar
/bin/sh: 1: bb: not found

    at checkExecSyncError (child_process.js:790:11)
    at Module.execSync (child_process.js:863:15)
    at file:///home/thomas/.config/yarn/global/node_modules/@logseq/rdf-export/node_modules/@logseq/nbb-logseq/lib/nbb_deps.js:5:94
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async file:///home/thomas/.config/yarn/global/node_modules/@logseq/rdf-export/rdf_export.mjs:9:18 {
  status: 127,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(26) [Uint8Array] [
       47,  98, 105, 110,  47, 115, 104,
       58,  32,  49,  58,  32,  98,  98,
       58,  32, 110, 111, 116,  32, 102,
      111, 117, 110, 100,  10
    ]
  ],
  pid: 6698,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(26) [Uint8Array] [
     47,  98, 105, 110,  47, 115, 104,
     58,  32,  49,  58,  32,  98,  98,
     58,  32, 110, 111, 116,  32, 102,
    111, 117, 110, 100,  10
  ]
}
```

I am not familiar with yarn which I had to install, maybe there is something else I need ?
Thanks

**Comment by tfrancart** [comment]
I tried `sudo apt install bb` but no luck, although I don't have the "command not found" message, the script still fails :

```
Downloading dependencies...
child_process.js:790
    err = new Error(msg);
          ^

Error: Command failed: bb --config /home/thomas/.config/yarn/global/node_modules/@logseq/rdf-export/.nbb/.cache/4ef27996850f7cca83b8c016709fa38b9216264a/deps.edn uberjar /home/thomas/.config/yarn/global/node_modules/@logseq/rdf-export/.nbb/.cache/4ef27996850f7cca83b8c016709fa38b9216264a/nbb-deps.jar
    at checkExecSyncError (child_process.js:790:11)
    at Module.execSync (child_process.js:863:15)
    at file:///home/thomas/.config/yarn/global/node_modules/@logseq/rdf-export/node_modules/@logseq/nbb-logseq/lib/nbb_deps.js:5:94
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async file:///home/thomas/.config/yarn/global/node_modules/@logseq/rdf-export/rdf_export.mjs:9:18 {
  status: 1,
...
```

**Comment by logseq-cldwalker** [comment]
Hi. Sorry. I just saw this. https://github.com/babashka/babashka#installation are the installation instructions for bb. I've updated the readme

**Comment by tfrancart** [comment]
Thanks, I was able to install bb with the "installer script" method (https://github.com/babashka/babashka#installer-script)
